apiVersion: apps/v1
kind: Deployment
metadata:
  name: edusence-backend
  labels:
    app: edusence-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edusence-backend
  template:
    metadata:
      labels:
        app: edusence-backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: edusence-backend
          image: ghcr.io/dheenaoo7/edusence-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: edusence-backend-secret
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: edusence-backend-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: edusence-backend-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: AWS_S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: edusence-backend-secret
                  key: AWS_S3_ACCESS_KEY
            - name: AWS_S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: edusence-backend-secret
                  key: AWS_S3_SECRET_KEY
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: edusence-backend-secret
                  key: GEMINI_API_KEY
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
