apiVersion: v1
kind: Service
metadata:
  name: edusence-backend
  labels:
    app: edusence-backend
spec:
  selector:
    app: edusence-backend
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
