apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edusence-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: edusence.contentflow.page
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: edusence-backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: edusence-frontend
                port:
                  number: 80
