apiVersion: v1
kind: Service
metadata:
  name: edusence-frontend
  labels:
    app: edusence-frontend
spec:
  selector:
    app: edusence-frontend
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
